### ISSUE TITLE
Implement UI Using Java Swing for Tic Tac Toe Game

### ISSUE THREAD

**Issue by Max-Meinel** [Max-Meinel/Tic-Tac-Toe#14]
## Explanation
Create a Java Swing-based user interface (UI) to enhance the visual presentation and user interaction in the Tic Tac Toe game.

## Proposed Changes
Design the game board layout using Java Swing components.
Integrate interactive elements for player moves and game state updates.
Ensure a responsive and intuitive UI for seamless gameplay experience.

**Comment by mazus187** [comment]
I want to work on that issue.
