### ISSUE TITLE
 Add functionality to restart the game after a win

### ISSUE THREAD

**Issue by Max-Meinel** [Max-Meinel/Tic-Tac-Toe#6]
### Explanation
Once a player wins, there's currently no way to restart the game without rerunning the program. This issue focuses on implementing a feature that allows players to restart the game without exiting the program.

### Proposed Changes
Introduce a method or functionality that resets the game board to its initial state when a player wins, allowing for a fresh start without relaunching the program.

**Comment by Gree44** [comment]
I would like to claim this issue.
