### ISSUE TITLE
Add functionality to detect a tie game (draw)

### ISSUE THREAD

**Issue by Max-Meinel** [Max-Meinel/Tic-Tac-Toe#7]
### Explanation
Currently, the game doesn't detect a tie when all cells are occupied without a winner. This issue aims to implement logic to recognize when the game ends in a tie.

### Proposed Changes
Modify the gameDone() method to check for a tie condition when all cells are filled without a win.
Display a message indicating a tie game when applicable.

**Comment by tryfdalk** [comment]
Hello, my name is Trifon and i am studying on Computer Science Department of Aristotle University of Thessaloniki and i would like to solve this issue to make my first contribution in open source code.

**Comment by Max-Meinel** [comment]
Hello Trifon! That's fantastic. I'd be happy to help you work on this issue for your first open-source contribution. Let's dive in and work together on resolving this issue. Feel free to ask any questions or if you need assistance along the way. Happy coding!

**Comment by Max-Meinel** [comment]
Hello Trifon, Thanks a lot for your contribution! I appreciate your efforts in improving the open-source code. If you have any questions or if there's anything else you'd like to collaborate on, feel free to let me know.
